fix: 'generate_completions_from_executable' does not support shell(s)
GeneratedCompletion is called with string values from `cask.jws.json` resulting in inadvertently incompatible operations on arrays strings and arrays of symbols.

This surfaces to the user as errors like:

```
Error: Cask '1password-cli' definition is invalid: 'generate_completions_from_executable' does not support shell(s): bash, zsh, fish, pwsh
```