feat(formula): allow skipping relocation
Many third-party formula have dependencies on binaries that cannot be
easily moved. I understand why we want to enforce relocation for
homebrew-core, but for external formulae I believe being able to opt out
is useful.

```
Error: Failed changing dylib ID of /opt/homebrew/Cellar/myformula/1.2.3/libexec/lib/python3.14/site-packages/cryptography/hazmat/bindings/_rust.abi3.so
  from @rpath/cryptography.hazmat.bindings._rust.abi3.so
    to /opt/homebrew/opt/myformula/libexec/lib/python3.14/site-packages/cryptography/hazmat/bindings/cryptography.hazmat.bindings._rust.abi3.so
Error: Failed to fix install linkage
Updated load commands do not fit in the header of .  needs to be relinked, possibly with -headerpad or -headerpad_max_install_names
The formula built, but you may encounter issues using it or linking other
formulae against it.
```